install.packages('plyr')
install.packages('tidyverse')
install.packages('ggpubr')
install.packages('scales')
install.packages('Metrics')
install.packages('arrow')
install.packages('lubridate')
install.packages('here')
install.packages('googlesheets4')
install.packages('aws.s3')
install.packages('IRkernel')
install.packages('gsheet')
install.packages('fable')
install.packages('scoringRules')
install.packages('remotes')
install.packages('rLakeAnalyzer')
install.packages('statcomp')
install.packages('rMR')
install.packages('RcppRoll')
install.packages('ggpmisc')
remotes::install_github('wwoelmer/FLAREr', ref = 'SUNP_MS_2023', force = TRUE)
install.packages('stringr', version = '1.4.0')
install.packages('vctrs')

